/**
 * Luo-Music Demo Plugin
 *
 * A small, installable plugin template that returns framework standard models.
 */

const DEMO_AUDIO_URL = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'
const DEFAULT_MAX_RESULTS = 10
const MAX_RESULTS_LIMIT = 50

let searchCount = 0

function normalizePositiveInteger(value, fallback) {
  const numberValue = Number(value)
  return Number.isFinite(numberValue) && numberValue > 0 ? Math.round(numberValue) : fallback
}

function createDemoSong(ctx, id, name, index = 0) {
  return {
    id,
    name,
    artists: [{ id: 'demo-artist', name: 'Demo Artist' }],
    album: {
      id: 'demo-album',
      name: 'Demo Album',
      picUrl: ''
    },
    duration: 180000 + index * 10000,
    mvid: 0,
    platform: ctx.platformId,
    originalId: id,
    extra: {
      template: true
    }
  }
}

export default {
  async create(ctx) {
    const { createPluginCallError, createSongUrlResult } = ctx.sdk
    ctx.logger.info('Demo plugin initialized', {
      platformId: ctx.platformId,
      settings: ctx.settings
    })

    const storedCount = await ctx.storage.get('searchCount')
    if (typeof storedCount === 'number' && Number.isFinite(storedCount)) {
      searchCount = storedCount
    }

    return {
      async search(input) {
        searchCount += 1
        await ctx.storage.set('searchCount', searchCount)

        const configuredLimit = normalizePositiveInteger(
          ctx.settings.maxResults,
          normalizePositiveInteger(input.limit, DEFAULT_MAX_RESULTS)
        )
        const limit = Math.min(configuredLimit, MAX_RESULTS_LIMIT)
        const page = normalizePositiveInteger(input.page, 1)
        const keyword = typeof input.keyword === 'string' ? input.keyword.trim() : ''

        if (!keyword) {
          throw createPluginCallError('PARSE_ERROR', 'Demo search keyword is required', {
            retryable: false,
            userMessage: '请输入搜索关键词'
          })
        }

        if (ctx.settings.verbose) {
          ctx.logger.debug('Searching demo catalog', {
            keyword,
            limit,
            page
          })
        }

        const results = Array.from({ length: limit }, (_, index) =>
          createDemoSong(ctx, `demo-${page}-${index}`, `[Demo] "${keyword}" 结果 ${index + 1}`, index)
        )

        return {
          list: results,
          total: results.length * 3
        }
      },

      async getSongUrl(input) {
        ctx.logger.info('Demo getSongUrl', { id: input.id })

        return createSongUrlResult(DEMO_AUDIO_URL, {
          mediaId: input.id,
          level: 'standard',
          bitrate: 128000
        })
      },

      async getSongDetail(input) {
        ctx.logger.info('Demo getSongDetail', { id: input.id })

        return createDemoSong(ctx, input.id, `[Demo] Song ${input.id}`)
      },

      async getLyric(input) {
        ctx.logger.info('Demo getLyric', { id: input.id })

        return {
          lrc: [
            '[00:00.00]Demo Plugin - 示例歌词',
            '[00:05.00]这是一首由 Demo 插件生成的示例歌曲',
            '[00:10.00]歌词内容仅用于演示插件接口',
            '[00:15.00]实际使用时请替换为真实歌词获取逻辑'
          ].join('\n'),
          tlyric: [
            '[00:00.00]Demo Plugin - Example Lyrics',
            '[00:05.00]This is a demo song generated by the Demo plugin',
            '[00:10.00]Lyrics are only for demonstrating the plugin interface',
            '[00:15.00]Replace with real lyric fetching logic in production'
          ].join('\n'),
          romalrc: ''
        }
      },

      async getPlaylistDetail() {
        throw createPluginCallError(
          'UNSUPPORTED_OPERATION',
          'Demo playlist detail is not supported',
          {
            retryable: false,
            userMessage: 'Demo 插件不支持歌单详情'
          }
        )
      },

      async dispose() {
        ctx.logger.info('Demo plugin disposed', { searchCount })
      }
    }
  }
}
