export const TIME_INTERVAL = {
  PROGRESS_UPDATE: 100,
  LYRIC_SYNC: 100,
  SKIP_COOLDOWN: 3000,
  FADE_DURATION: 200
} as const

export const SKIP_CONFIG = {
  MAX_ATTEMPTS: 5,
  COOLDOWN_MS: 3000,
  MAX_UNAVAILABLE_RATIO: 0.8
} as const
