/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CacheManager: typeof import('./components/CacheManager.vue')['default']
    Lyric: typeof import('./components/Lyric.vue')['default']
    PageTransition: typeof import('./components/PageTransition.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playlist: typeof import('./components/Playlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}
