/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumDetailPanel: typeof import('./components/user/AlbumDetailPanel.vue')['default']
    CacheManager: typeof import('./components/CacheManager.vue')['default']
    ErrorToast: typeof import('./components/ErrorToast.vue')['default']
    EventsView: typeof import('./components/user/EventsView.vue')['default']
    FavoriteAlbumsView: typeof import('./components/user/FavoriteAlbumsView.vue')['default']
    HomeBrandBadge: typeof import('./components/home/HomeBrandBadge.vue')['default']
    HomeCollectionDetailPanel: typeof import('./components/home/HomeCollectionDetailPanel.vue')['default']
    HomeFooter: typeof import('./components/home/HomeFooter.vue')['default']
    HomeHeader: typeof import('./components/home/HomeHeader.vue')['default']
    HomeLikedSongsPanel: typeof import('./components/home/HomeLikedSongsPanel.vue')['default']
    HomeLocalMusicPanel: typeof import('./components/home/HomeLocalMusicPanel.vue')['default']
    HomeSearchBar: typeof import('./components/home/HomeSearchBar.vue')['default']
    HomeServerSelect: typeof import('./components/home/HomeServerSelect.vue')['default']
    HomeSettingsPanel: typeof import('./components/home/HomeSettingsPanel.vue')['default']
    HomeSidebar: typeof import('./components/home/HomeSidebar.vue')['default']
    HomeSidebarFooter: typeof import('./components/home/HomeSidebarFooter.vue')['default']
    HomeTabBar: typeof import('./components/home/HomeTabBar.vue')['default']
    HomeWindowControls: typeof import('./components/home/HomeWindowControls.vue')['default']
    HomeWorkspace: typeof import('./components/home/HomeWorkspace.vue')['default']
    LikedSongsView: typeof import('./components/user/LikedSongsView.vue')['default']
    LocalMusicEmptyState: typeof import('./components/home/local-music/LocalMusicEmptyState.vue')['default']
    LocalMusicFolderList: typeof import('./components/home/local-music/LocalMusicFolderList.vue')['default']
    LocalMusicHero: typeof import('./components/home/local-music/LocalMusicHero.vue')['default']
    LocalMusicSongsView: typeof import('./components/home/local-music/LocalMusicSongsView.vue')['default']
    LocalMusicSummaryGrid: typeof import('./components/home/local-music/LocalMusicSummaryGrid.vue')['default']
    LocalMusicToolbar: typeof import('./components/home/local-music/LocalMusicToolbar.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    LyricDisplay: typeof import('./components/LyricDisplay.vue')['default']
    LyricFloat: typeof import('./components/LyricFloat.vue')['default']
    PageTransition: typeof import('./components/PageTransition.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playlist: typeof import('./components/Playlist.vue')['default']
    PlaylistDetailPanel: typeof import('./components/user/PlaylistDetailPanel.vue')['default']
    PlaylistsView: typeof import('./components/user/PlaylistsView.vue')['default']
    QQLoginModal: typeof import('./components/QQLoginModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    SongDetailList: typeof import('./components/user/SongDetailList.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
    UserProfileHeader: typeof import('./components/user/UserProfileHeader.vue')['default']
  }
}
