/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CacheManager: typeof import('./components/CacheManager.vue')['default']
    EventsView: typeof import('./components/user/EventsView.vue')['default']
    LikedSongsView: typeof import('./components/user/LikedSongsView.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    Lyric: typeof import('./components/Lyric.vue')['default']
    PageTransition: typeof import('./components/PageTransition.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playlist: typeof import('./components/Playlist.vue')['default']
    PlaylistsView: typeof import('./components/user/PlaylistsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserCenter: typeof import('./components/UserCenter.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
    UserProfileHeader: typeof import('./components/user/UserProfileHeader.vue')['default']
  }
}
