import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const require = createRequire(import.meta.url)
const {
  createBitPerfectCandidateWavBuffer,
  normalizeAutoWavFormat,
  parseBooleanEnv,
  resolveAutoGeneratedAudioFilePath
} = require('../../scripts/test-audio-output-bit-perfect-candidate.cjs') as {
  createBitPerfectCandidateWavBuffer: (options: {
    sampleRate: number
    channels: number
    sampleFormat: string
    bitDepth: number
    durationSeconds?: number
  }) => Buffer
  normalizeAutoWavFormat: (format: {
    sampleRate?: unknown
    channels?: unknown
    sampleFormat?: unknown
    bitDepth?: unknown
  }) => {
    sampleRate: number
    channels: number
    sampleFormat: 'pcm' | 'float'
    bitDepth: number
  }
  parseBooleanEnv: (
    name: string,
    fallback: boolean,
    env?: Record<string, string | undefined>
  ) => boolean
  resolveAutoGeneratedAudioFilePath: (
    reportPath?: string | null,
    env?: Record<string, string | undefined>
  ) => {
    path: string
    retained: boolean
    source: string
  }
}

const script = readFileSync(
  resolve(process.cwd(), 'scripts/test-audio-output-bit-perfect-candidate.cjs'),
  'utf8'
)

describe('audio output bit-perfect candidate script', () => {
  it('waits for diagnostics that belong to the requested playback', () => {
    expect(script).toContain('event.payload?.nativePlaybackSource === resolvedAudioFilePath')
    expect(script).toContain('playbackDiagnosticStates.has(event.payload?.nativePlaybackState)')
    expect(script).toContain("'ended'")
  })

  it('marks candidate reports as requiring external proof', () => {
    expect(script).toContain("proof: 'candidate-only'")
    expect(script).toContain('requiresExternalVerification: true')
    expect(script).toContain('audioFileIdentity')
    expect(script).toContain('sha256: await hashFile(resolvedAudioFilePath)')
  })

  it('can enable the helper bit-perfect candidate guard', () => {
    expect(script).toContain('LUO_AUDIO_OUTPUT_BIT_PERFECT_REQUIRE_CANDIDATE')
    expect(script).toContain('bitPerfectRequired')
    expect(script).toContain("event.payload?.nativePlaybackState === 'error'")
  })

  it('can auto-generate a WASAPI-format-matched WAV candidate source', () => {
    expect(script).toContain('LUO_AUDIO_OUTPUT_BIT_PERFECT_AUTO_WAV')
    expect(script).toContain('LUO_AUDIO_OUTPUT_BIT_PERFECT_AUTO_WAV_PATH')
    expect(script).toContain('discoverExclusiveOutputFormat')
    expect(script).toContain('createBitPerfectCandidateWavBuffer')
    expect(script).toContain('discoveredOutputFormat')
    expect(script).toContain('autoGeneratedAudioFile')
  })

  it('can persist candidate reports for loopback verification', () => {
    expect(script).toContain('LUO_AUDIO_OUTPUT_BIT_PERFECT_REPORT')
    expect(script).toContain('resolveReportPathFromEnv')
    expect(script).toContain("'bitPerfect'")
    expect(script).toContain('writeReportIfRequested')
    expect(script).toContain('fs.mkdirSync(path.dirname(report.reportPath), { recursive: true })')
    expect(script).toContain('fs.writeFileSync(report.reportPath')
    expect(script).toContain('reportPath: reportPath ?? undefined')
    expect(script).toContain('prepareAudioOutputHelper')
    expect(script).toContain('helperPathSource')
  })

  it('creates PCM and float WAV buffers with stable headers', () => {
    const pcm = createBitPerfectCandidateWavBuffer({
      sampleRate: 48000,
      channels: 2,
      sampleFormat: 'pcm',
      bitDepth: 24,
      durationSeconds: 0.05
    })
    expect(pcm.subarray(0, 4).toString('ascii')).toBe('RIFF')
    expect(pcm.subarray(8, 12).toString('ascii')).toBe('WAVE')
    expect(pcm.readUInt16LE(20)).toBe(1)
    expect(pcm.readUInt16LE(22)).toBe(2)
    expect(pcm.readUInt32LE(24)).toBe(48000)
    expect(pcm.readUInt16LE(34)).toBe(24)

    const float = createBitPerfectCandidateWavBuffer({
      sampleRate: 44100,
      channels: 1,
      sampleFormat: 'float',
      bitDepth: 32,
      durationSeconds: 0.05
    })
    expect(float.readUInt16LE(20)).toBe(3)
    expect(float.readUInt16LE(22)).toBe(1)
    expect(float.readUInt32LE(24)).toBe(44100)
    expect(float.readUInt16LE(34)).toBe(32)
  })

  it('normalizes supported auto WAV formats from helper diagnostics', () => {
    expect(
      normalizeAutoWavFormat({
        sampleRate: 48000,
        channels: 2,
        sampleFormat: 'pcm',
        bitDepth: 24
      })
    ).toEqual({
      sampleRate: 48000,
      channels: 2,
      sampleFormat: 'pcm',
      bitDepth: 24
    })

    expect(
      normalizeAutoWavFormat({
        sampleRate: 44100,
        channels: 2,
        sampleFormat: 'f32',
        bitDepth: 32
      })
    ).toMatchObject({
      sampleFormat: 'float',
      bitDepth: 32
    })
    expect(() =>
      normalizeAutoWavFormat({
        sampleRate: 48000,
        channels: 2,
        sampleFormat: 'float',
        bitDepth: 64
      })
    ).toThrow('Unsupported auto WAV float bit depth')
  })

  it('keeps auto-generated WAV beside saved reports for loopback capture', () => {
    expect(resolveAutoGeneratedAudioFilePath('D:\\Captures\\candidate.json', {})).toEqual({
      path: resolve('D:\\Captures\\candidate.source.wav'),
      retained: true,
      source: 'report-path'
    })
    expect(
      resolveAutoGeneratedAudioFilePath(null, {
        LUO_AUDIO_OUTPUT_BIT_PERFECT_AUTO_WAV_PATH: 'D:\\Captures\\source.wav'
      })
    ).toEqual({
      path: resolve('D:\\Captures\\source.wav'),
      retained: true,
      source: 'LUO_AUDIO_OUTPUT_BIT_PERFECT_AUTO_WAV_PATH'
    })
  })

  it('accepts explicit boolean values for auto WAV mode', () => {
    expect(parseBooleanEnv('AUTO', false, {})).toBe(false)
    expect(parseBooleanEnv('AUTO', true, {})).toBe(true)
    expect(parseBooleanEnv('AUTO', false, { AUTO: '1' })).toBe(true)
    expect(parseBooleanEnv('AUTO', false, { AUTO: 'yes' })).toBe(true)
    expect(parseBooleanEnv('AUTO', true, { AUTO: '0' })).toBe(false)
  })
})
